namespace PortScanner;

partial class Form1
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        this.lblStart = new System.Windows.Forms.Label();
        this.lblEnd = new System.Windows.Forms.Label();
        this.txtStartIp = new System.Windows.Forms.TextBox();
        this.txtEndIp = new System.Windows.Forms.TextBox();
        this.lblWorkers = new System.Windows.Forms.Label();
        this.numWorkers = new System.Windows.Forms.NumericUpDown();
        this.chkDns = new System.Windows.Forms.CheckBox();
        this.chkPortScan = new System.Windows.Forms.CheckBox();
        this.txtPorts = new System.Windows.Forms.TextBox();
        this.btnStart = new System.Windows.Forms.Button();
        this.btnStop = new System.Windows.Forms.Button();
        this.chkUseMask = new System.Windows.Forms.CheckBox();
        this.btnClearOutput = new System.Windows.Forms.Button();
        this.btnClearLog = new System.Windows.Forms.Button();
        this.btnExportCsv = new System.Windows.Forms.Button();
        this.btnExportJson = new System.Windows.Forms.Button();
        this.btnExportXml = new System.Windows.Forms.Button();
        this.lblStatusFilter = new System.Windows.Forms.Label();
        this.cmbStatus = new System.Windows.Forms.ComboBox();
        this.btnApplyFilter = new System.Windows.Forms.Button();
        this.btnClearFilter = new System.Windows.Forms.Button();
        this.lblIpFilter = new System.Windows.Forms.Label();
        this.txtFilterIp = new System.Windows.Forms.TextBox();
        this.lblHostFilter = new System.Windows.Forms.Label();
        this.txtFilterHost = new System.Windows.Forms.TextBox();
        this.lblRttMin = new System.Windows.Forms.Label();
        this.txtRttMin = new System.Windows.Forms.TextBox();
        this.lblRttMax = new System.Windows.Forms.Label();
        this.txtRttMax = new System.Windows.Forms.TextBox();
        this.lvResults = new System.Windows.Forms.ListView();
        this.colIp = new System.Windows.Forms.ColumnHeader();
        this.colStatus = new System.Windows.Forms.ColumnHeader();
        this.colRtt = new System.Windows.Forms.ColumnHeader();
        this.colHostname = new System.Windows.Forms.ColumnHeader();
        this.rtbLog = new System.Windows.Forms.RichTextBox();
        ((System.ComponentModel.ISupportInitialize)(this.numWorkers)).BeginInit();
        this.SuspendLayout();
        this.lblStart.AutoSize = true;
        this.lblStart.Location = new System.Drawing.Point(12, 13);
        this.lblStart.Name = "lblStart";
        this.lblStart.Size = new System.Drawing.Size(48, 15);
        this.lblStart.TabIndex = 0;
        this.lblStart.Text = "Start IP";
        this.lblEnd.AutoSize = true;
        this.lblEnd.Location = new System.Drawing.Point(12, 42);
        this.lblEnd.Name = "lblEnd";
        this.lblEnd.Size = new System.Drawing.Size(44, 15);
        this.lblEnd.TabIndex = 1;
        this.lblEnd.Text = "End IP";
        this.txtStartIp.Location = new System.Drawing.Point(80, 10);
        this.txtStartIp.Name = "txtStartIp";
        this.txtStartIp.Size = new System.Drawing.Size(160, 23);
        this.txtStartIp.TabIndex = 2;
        this.txtStartIp.Text = "172.0.0.0";
        this.txtEndIp.Location = new System.Drawing.Point(80, 39);
        this.txtEndIp.Name = "txtEndIp";
        this.txtEndIp.Size = new System.Drawing.Size(160, 23);
        this.txtEndIp.TabIndex = 3;
        this.txtEndIp.Text = "172.0.0.255";
        this.lblWorkers.AutoSize = true;
        this.lblWorkers.Location = new System.Drawing.Point(260, 13);
        this.lblWorkers.Name = "lblWorkers";
        this.lblWorkers.Size = new System.Drawing.Size(52, 15);
        this.lblWorkers.TabIndex = 4;
        this.lblWorkers.Text = "Workery";
        this.numWorkers.Location = new System.Drawing.Point(320, 10);
        this.numWorkers.Maximum = new decimal(new int[] {500,0,0,0});
        this.numWorkers.Minimum = new decimal(new int[] {1,0,0,0});
        this.numWorkers.Name = "numWorkers";
        this.numWorkers.Size = new System.Drawing.Size(80, 23);
        this.numWorkers.TabIndex = 5;
        this.numWorkers.Value = new decimal(new int[] {100,0,0,0});
        this.chkDns.AutoSize = true;
        this.chkDns.Location = new System.Drawing.Point(260, 42);
        this.chkDns.Name = "chkDns";
        this.chkDns.Size = new System.Drawing.Size(85, 19);
        this.chkDns.TabIndex = 6;
        this.chkDns.Text = "DNS lookup";
        this.chkDns.UseVisualStyleBackColor = true;
        this.chkPortScan.AutoSize = true;
        this.chkPortScan.Location = new System.Drawing.Point(360, 42);
        this.chkPortScan.Name = "chkPortScan";
        this.chkPortScan.Size = new System.Drawing.Size(90, 19);
        this.chkPortScan.TabIndex = 7;
        this.chkPortScan.Text = "Scan portů";
        this.chkPortScan.UseVisualStyleBackColor = true;
        this.txtPorts.Location = new System.Drawing.Point(456, 40);
        this.txtPorts.Name = "txtPorts";
        this.txtPorts.Size = new System.Drawing.Size(140, 23);
        this.txtPorts.TabIndex = 8;
        this.txtPorts.Text = "80,443";
        this.btnStart.Location = new System.Drawing.Point(620, 10);
        this.btnStart.Name = "btnStart";
        this.btnStart.Size = new System.Drawing.Size(80, 23);
        this.btnStart.TabIndex = 9;
        this.btnStart.Text = "Start";
        this.btnStart.UseVisualStyleBackColor = true;
        this.btnStart.Click += new System.EventHandler(this.btnStart_Click);
        this.btnStop.Location = new System.Drawing.Point(706, 10);
        this.btnStop.Name = "btnStop";
        this.btnStop.Size = new System.Drawing.Size(80, 23);
        this.btnStop.TabIndex = 10;
        this.btnStop.Text = "Stop";
        this.btnStop.UseVisualStyleBackColor = true;
        this.btnStop.Click += new System.EventHandler(this.btnStop_Click);
        this.chkUseMask.AutoSize = true;
        this.chkUseMask.Location = new System.Drawing.Point(540, 12);
        this.chkUseMask.Name = "chkUseMask";
        this.chkUseMask.Size = new System.Drawing.Size(78, 19);
        this.chkUseMask.TabIndex = 9;
        this.chkUseMask.Text = "Síť/maska";
        this.chkUseMask.UseVisualStyleBackColor = true;
        this.chkUseMask.CheckedChanged += new System.EventHandler(this.chkUseMask_CheckedChanged);
        this.btnClearOutput.Location = new System.Drawing.Point(620, 40);
        this.btnClearOutput.Name = "btnClearOutput";
        this.btnClearOutput.Size = new System.Drawing.Size(80, 23);
        this.btnClearOutput.TabIndex = 11;
        this.btnClearOutput.Text = "Clear";
        this.btnClearOutput.UseVisualStyleBackColor = true;
        this.btnClearOutput.Click += new System.EventHandler(this.btnClearOutput_Click);
        this.btnClearLog.Location = new System.Drawing.Point(706, 40);
        this.btnClearLog.Name = "btnClearLog";
        this.btnClearLog.Size = new System.Drawing.Size(80, 23);
        this.btnClearLog.TabIndex = 12;
        this.btnClearLog.Text = "Clear Log";
        this.btnClearLog.UseVisualStyleBackColor = true;
        this.btnClearLog.Click += new System.EventHandler(this.btnClearLog_Click);
        this.btnExportCsv.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
        this.btnExportCsv.Location = new System.Drawing.Point(12, 72);
        this.btnExportCsv.Name = "btnExportCsv";
        this.btnExportCsv.Size = new System.Drawing.Size(80, 23);
        this.btnExportCsv.TabIndex = 13;
        this.btnExportCsv.Text = "Export CSV";
        this.btnExportCsv.UseVisualStyleBackColor = true;
        this.btnExportCsv.Click += new System.EventHandler(this.btnExportCsv_Click);
        this.btnExportJson.Location = new System.Drawing.Point(98, 72);
        this.btnExportJson.Name = "btnExportJson";
        this.btnExportJson.Size = new System.Drawing.Size(100, 23);
        this.btnExportJson.TabIndex = 14;
        this.btnExportJson.Text = "Export JSON";
        this.btnExportJson.UseVisualStyleBackColor = true;
        this.btnExportJson.Click += new System.EventHandler(this.btnExportJson_Click);
        this.btnExportXml.Location = new System.Drawing.Point(204, 72);
        this.btnExportXml.Name = "btnExportXml";
        this.btnExportXml.Size = new System.Drawing.Size(100, 23);
        this.btnExportXml.TabIndex = 15;
        this.btnExportXml.Text = "Export XML";
        this.btnExportXml.UseVisualStyleBackColor = true;
        this.btnExportXml.Click += new System.EventHandler(this.btnExportXml_Click);
        this.lblStatusFilter.AutoSize = true;
        this.lblStatusFilter.Location = new System.Drawing.Point(320, 76);
        this.lblStatusFilter.Name = "lblStatusFilter";
        this.lblStatusFilter.Size = new System.Drawing.Size(37, 15);
        this.lblStatusFilter.TabIndex = 18;
        this.lblStatusFilter.Text = "Stav";
        this.cmbStatus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        this.cmbStatus.FormattingEnabled = true;
        this.cmbStatus.Items.AddRange(new object[] {
            "All",
            "Online",
            "Offline",
            "Timeout",
            "Error"});
        this.cmbStatus.Location = new System.Drawing.Point(370, 72);
        this.cmbStatus.Name = "cmbStatus";
        this.cmbStatus.Size = new System.Drawing.Size(120, 23);
        this.cmbStatus.TabIndex = 19;
        this.cmbStatus.SelectedIndex = 0;
        this.btnApplyFilter.Location = new System.Drawing.Point(620, 72);
        this.btnApplyFilter.Name = "btnApplyFilter";
        this.btnApplyFilter.Size = new System.Drawing.Size(80, 23);
        this.btnApplyFilter.TabIndex = 20;
        this.btnApplyFilter.Text = "Filtrovat";
        this.btnApplyFilter.UseVisualStyleBackColor = true;
        this.btnApplyFilter.Click += new System.EventHandler(this.btnApplyFilter_Click);
        this.btnClearFilter.Location = new System.Drawing.Point(706, 72);
        this.btnClearFilter.Name = "btnClearFilter";
        this.btnClearFilter.Size = new System.Drawing.Size(80, 23);
        this.btnClearFilter.TabIndex = 21;
        this.btnClearFilter.Text = "Reset filt.";
        this.btnClearFilter.UseVisualStyleBackColor = true;
        this.btnClearFilter.Click += new System.EventHandler(this.btnClearFilter_Click);
        this.lblIpFilter.AutoSize = true;
        this.lblIpFilter.Location = new System.Drawing.Point(12, 103);
        this.lblIpFilter.Name = "lblIpFilter";
        this.lblIpFilter.Size = new System.Drawing.Size(51, 15);
        this.lblIpFilter.TabIndex = 22;
        this.lblIpFilter.Text = "IP filtr";
        this.txtFilterIp.Location = new System.Drawing.Point(80, 100);
        this.txtFilterIp.Name = "txtFilterIp";
        this.txtFilterIp.Size = new System.Drawing.Size(140, 23);
        this.txtFilterIp.TabIndex = 23;
        this.lblHostFilter.AutoSize = true;
        this.lblHostFilter.Location = new System.Drawing.Point(230, 103);
        this.lblHostFilter.Name = "lblHostFilter";
        this.lblHostFilter.Size = new System.Drawing.Size(84, 15);
        this.lblHostFilter.TabIndex = 24;
        this.lblHostFilter.Text = "Hostname filtr";
        this.txtFilterHost.Location = new System.Drawing.Point(320, 100);
        this.txtFilterHost.Name = "txtFilterHost";
        this.txtFilterHost.Size = new System.Drawing.Size(170, 23);
        this.txtFilterHost.TabIndex = 25;
        this.lblRttMin.AutoSize = true;
        this.lblRttMin.Location = new System.Drawing.Point(500, 103);
        this.lblRttMin.Name = "lblRttMin";
        this.lblRttMin.Size = new System.Drawing.Size(55, 15);
        this.lblRttMin.TabIndex = 26;
        this.lblRttMin.Text = "RTT min";
        this.txtRttMin.Location = new System.Drawing.Point(560, 100);
        this.txtRttMin.Name = "txtRttMin";
        this.txtRttMin.Size = new System.Drawing.Size(60, 23);
        this.txtRttMin.TabIndex = 27;
        this.lblRttMax.AutoSize = true;
        this.lblRttMax.Location = new System.Drawing.Point(630, 103);
        this.lblRttMax.Name = "lblRttMax";
        this.lblRttMax.Size = new System.Drawing.Size(58, 15);
        this.lblRttMax.TabIndex = 28;
        this.lblRttMax.Text = "RTT max";
        this.txtRttMax.Location = new System.Drawing.Point(690, 100);
        this.txtRttMax.Name = "txtRttMax";
        this.txtRttMax.Size = new System.Drawing.Size(60, 23);
        this.txtRttMax.TabIndex = 29;
        this.lvResults.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
        this.lvResults.Location = new System.Drawing.Point(12, 131);
        this.lvResults.Name = "lvResults";
        this.lvResults.Size = new System.Drawing.Size(774, 220);
        this.lvResults.TabIndex = 16;
        this.lvResults.View = System.Windows.Forms.View.Details;
        this.lvResults.FullRowSelect = true;
        this.lvResults.GridLines = true;
        this.lvResults.VirtualMode = true;
        this.lvResults.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] { this.colIp, this.colStatus, this.colRtt, this.colHostname });
        this.lvResults.ColumnClick += new System.Windows.Forms.ColumnClickEventHandler(this.lvResults_ColumnClick);
        this.lvResults.RetrieveVirtualItem += new System.Windows.Forms.RetrieveVirtualItemEventHandler(this.lvResults_RetrieveVirtualItem);
        this.colIp.Text = "IP adresa";
        this.colIp.Width = 160;
        this.colStatus.Text = "Stav";
        this.colStatus.Width = 100;
        this.colRtt.Text = "RTT (ms)";
        this.colRtt.Width = 100;
        this.colHostname.Text = "Hostname";
        this.colHostname.Width = 300;
        this.rtbLog.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
        this.rtbLog.Location = new System.Drawing.Point(12, 357);
        this.rtbLog.Name = "rtbLog";
        this.rtbLog.ReadOnly = true;
        this.rtbLog.Size = new System.Drawing.Size(774, 81);
        this.rtbLog.TabIndex = 17;
        this.rtbLog.Text = "";
        this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        this.ClientSize = new System.Drawing.Size(800, 450);
        this.Controls.Add(this.txtRttMax);
        this.Controls.Add(this.lblRttMax);
        this.Controls.Add(this.txtRttMin);
        this.Controls.Add(this.lblRttMin);
        this.Controls.Add(this.txtFilterHost);
        this.Controls.Add(this.lblHostFilter);
        this.Controls.Add(this.txtFilterIp);
        this.Controls.Add(this.lblIpFilter);
        this.Controls.Add(this.btnClearFilter);
        this.Controls.Add(this.btnApplyFilter);
        this.Controls.Add(this.cmbStatus);
        this.Controls.Add(this.lblStatusFilter);
        this.Controls.Add(this.rtbLog);
        this.Controls.Add(this.lvResults);
        this.Controls.Add(this.btnExportXml);
        this.Controls.Add(this.btnExportJson);
        this.Controls.Add(this.btnExportCsv);
        this.Controls.Add(this.btnClearLog);
        this.Controls.Add(this.btnClearOutput);
        this.Controls.Add(this.chkUseMask);
        this.Controls.Add(this.btnStop);
        this.Controls.Add(this.btnStart);
        this.Controls.Add(this.txtPorts);
        this.Controls.Add(this.chkPortScan);
        this.Controls.Add(this.chkDns);
        this.Controls.Add(this.numWorkers);
        this.Controls.Add(this.lblWorkers);
        this.Controls.Add(this.txtEndIp);
        this.Controls.Add(this.txtStartIp);
        this.Controls.Add(this.lblEnd);
        this.Controls.Add(this.lblStart);
        this.Name = "Form1";
        this.Text = "Paralelní LAN Scanner";
        ((System.ComponentModel.ISupportInitialize)(this.numWorkers)).EndInit();
        this.ResumeLayout(false);
        this.PerformLayout();
    }

    private System.Windows.Forms.Label lblStart;
    private System.Windows.Forms.Label lblEnd;
    private System.Windows.Forms.TextBox txtStartIp;
    private System.Windows.Forms.TextBox txtEndIp;
    private System.Windows.Forms.Label lblWorkers;
    private System.Windows.Forms.NumericUpDown numWorkers;
    private System.Windows.Forms.CheckBox chkDns;
    private System.Windows.Forms.CheckBox chkPortScan;
    private System.Windows.Forms.TextBox txtPorts;
    private System.Windows.Forms.Button btnStart;
    private System.Windows.Forms.Button btnStop;
    private System.Windows.Forms.Button btnClearOutput;
    private System.Windows.Forms.Button btnClearLog;
    private System.Windows.Forms.Button btnExportCsv;
    private System.Windows.Forms.Button btnExportJson;
    private System.Windows.Forms.Button btnExportXml;
    private System.Windows.Forms.Label lblStatusFilter;
    private System.Windows.Forms.ComboBox cmbStatus;
    private System.Windows.Forms.Button btnApplyFilter;
    private System.Windows.Forms.Button btnClearFilter;
    private System.Windows.Forms.Label lblIpFilter;
    private System.Windows.Forms.TextBox txtFilterIp;
    private System.Windows.Forms.Label lblHostFilter;
    private System.Windows.Forms.TextBox txtFilterHost;
    private System.Windows.Forms.Label lblRttMin;
    private System.Windows.Forms.TextBox txtRttMin;
    private System.Windows.Forms.Label lblRttMax;
    private System.Windows.Forms.TextBox txtRttMax;
    private System.Windows.Forms.ListView lvResults;
    private System.Windows.Forms.ColumnHeader colIp;
    private System.Windows.Forms.ColumnHeader colStatus;
    private System.Windows.Forms.ColumnHeader colRtt;
    private System.Windows.Forms.ColumnHeader colHostname;
    private System.Windows.Forms.RichTextBox rtbLog;
    private System.Windows.Forms.CheckBox chkUseMask;
}
